seed: 42
parallel: false
batch_size: 32
num_workers: 4
clf_lam: 1.0
reconstruction_lam: 1.0
kfold: 5
num_epochs: 100
embed_only: false
early_stop: 10
use_nucs: true
target: dock # dock or native_fp or is_native
shuffle: true
loss: 'l2'
use_rnamigos1_train: False
use_rnamigos1_ligands: False
rnamigos1_split: 0
