edge_types:
  - 'B53'
  - 'B35'
  - 'CWW'
  - 'CWH'
  - 'CWS'
  - 'CHW'
  - 'CHH'
  - 'CHS'
  - 'CSW'
  - 'CSH'
  - 'CSS'
  - 'TWW'
  - 'TWH'
  - 'TWS'
  - 'THW'
  - 'THH'
  - 'THS'
  - 'TSW'
  - 'TSH'
  - 'TSS'

nuc_types:
  - 'A'
  - 'U'
  - 'C'
  - 'G'
  - 'N'
