encoder:
  in_dim: 4
  hidden_dim: 32
  num_layers: 3
  num_bases: -1
  subset_pocket_nodes: True

lig_encoder:
  in_dim: 166
  hidden_dim: 32
  num_layers: 3

decoder:
  in_dim: 64 
  out_dim: 1 
  hidden_dim: 32
  num_layers: 3
  activation: sigmoid 

pool: 'att'
dropout: 0.2
batch_norm: True
use_pretrained: False
pretrained_path: pretrained/R_1_16/model.pth
