encoder:
  in_dim: 4
  hidden_dim: 32 
  num_layers: 3

lig_encoder:
  in_dim: 166
  hidden_dim: 32
  num_layers: 3

decoder:
  in_dim: 64 
  out_dim: 1 
  hidden_dim: 32
  num_layers: 3

pool: 'att'
use_pretrained: false
pretrained_path: pretrained/pretrained_model_graphlet.pth
