debug: false
name: final_chembl_dock_graphligs_dim64_simhungarian_prew0_optimol1_quant_stretch0
device: 2
verbose: false
tokens:
  edge_types:
  - B53
  - B35
  - CWW
  - CWH
  - CWS
  - CHW
  - CHH
  - CHS
  - CSW
  - CSH
  - CSS
  - TWW
  - TWH
  - TWS
  - THW
  - THH
  - THS
  - TSW
  - TSH
  - TSS
  nuc_types:
  - A
  - U
  - C
  - G
train:
  seed: 42
  parallel: false
  batch_size: 32
  num_workers: 2
  clf_lam: 1.0
  reconstruction_lam: 1.0
  kfold: 5
  num_epochs: 25
  embed_only: false
  early_stop: 20
  use_nucs: true
  target: dock
  use_normalized_score: true
  stretch_scores: 0
  shuffle: true
  loss: l2
  use_rnamigos1_train: false
  use_rnamigos1_ligands: false
  rnamigos1_split: -1
  learning_rate: 0.001
  pretrain_weight: 0
  simfunc: None
  simfunc_depth: 2
  max_kernel: 20
paths:
  model_path: models/
  pretrain_save: pretrained/
data:
  pocket_graphs: data/json_pockets_annotated
  pretrain_graphs: data/pretrain_data/data/annotated/NR_chops_annot
  ligand_db: data/ligand_db
  rnamigos1_test: false
  rnamigos1_only: false
  undirected: false
model:
  encoder:
    in_dim: 4
    hidden_dim: 64
    num_layers: 3
    num_bases: -1
    subset_pocket_nodes: true
  lig_encoder:
    in_dim: 166
    hidden_dim: 32
    num_layers: 3
  graphlig_encoder:
    use_pretrained: true
    features_dim: 22
    gcn_hdim: 32
    gcn_layers: 3
    l_size: 32
  decoder:
    in_dim: 120
    out_dim: 1
    hidden_dim: 32
    num_layers: 3
    activation: None
  pool: att
  dropout: 0.2
  batch_norm: true
  use_pretrained: true
  pretrained_path: pretrained/pretrain_hungarian_64/model.pth
  use_graphligs: true
